spring:
  application:
    name: redis_pub_sub_demo
  data:
    redis:
      host: ${REDIS_URL}
      port: 6379
      lettuce:
        pool:
          enabled: true
          max-total: 1000
          max-idle: 500
          min-idle: 100
          max-wait: 1000ms

logging:
  level:
    root: INFO
    io.netty: DEBUG